package de.intevation.lada.model;

// Generated 24.06.2013 16:31:53 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;


/**
 * Auth generated by hbm2java
 */
@Entity
@Table(name = "auth", schema = "public")
public class Auth
implements java.io.Serializable
{

    private int            id;
    private SMessStelle    SMessStelle;
    private SNetzBetreiber SNetzBetreiber;
    private String         ldapGroup;

    public Auth() {
    }

    public Auth(int id, String ldapGroup) {
        this.id = id;
        this.ldapGroup = ldapGroup;
    }

    public Auth(
        int id,
        SMessStelle SMessStelle,
        SNetzBetreiber SNetzBetreiber,
        String ldapGroup) {
        this.id = id;
        this.SMessStelle = SMessStelle;
        this.SNetzBetreiber = SNetzBetreiber;
        this.ldapGroup = ldapGroup;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "mst_id")
    public SMessStelle getSMessStelle() {
        return this.SMessStelle;
    }

    public void setSMessStelle(SMessStelle SMessStelle) {
        this.SMessStelle = SMessStelle;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "netzbetreiber_id")
    public SNetzBetreiber getSNetzBetreiber() {
        return this.SNetzBetreiber;
    }

    public void setSNetzBetreiber(SNetzBetreiber SNetzBetreiber) {
        this.SNetzBetreiber = SNetzBetreiber;
    }

    @Column(name = "ldap_group", nullable = false, length = 40)
    public String getLdapGroup() {
        return this.ldapGroup;
    }

    public void setLdapGroup(String ldapGroup) {
        this.ldapGroup = ldapGroup;
    }

}
