package de.intevation.lada.model;

// Generated 21.05.2013 16:58:30 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LKommentarP generated by hbm2java
 */
@Entity
@Table(name = "l_kommentar_p", schema = "public")
public class LKommentarP implements java.io.Serializable {

	private LKommentarPId id;
	private String probeId;
	private String erzeuger;
	private Date KDatum;
	private String KText;

	public LKommentarP() {
	}

	public LKommentarP(LKommentarPId id, String probeId, String erzeuger,
			Date KDatum) {
		this.id = id;
		this.probeId = probeId;
		this.erzeuger = erzeuger;
		this.KDatum = KDatum;
	}

	public LKommentarP(LKommentarPId id, String probeId, String erzeuger,
			Date KDatum, String KText) {
		this.id = id;
		this.probeId = probeId;
		this.erzeuger = erzeuger;
		this.KDatum = KDatum;
		this.KText = KText;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "probeId", column = @Column(name = "probe_id", nullable = false, length = 20)),
			@AttributeOverride(name = "KId", column = @Column(name = "k_id", nullable = false)) })
	public LKommentarPId getId() {
		return this.id;
	}

	public void setId(LKommentarPId id) {
		this.id = id;
	}

	@Column(name = "probe_id", nullable = false, insertable = false, updatable = false)
	public String getProbeId() {
		return this.probeId;
	}

	public void setProbeId(String probeId) {
		this.probeId = probeId;
	}

	@Column(name = "erzeuger", nullable = false, length = 5)
	public String getErzeuger() {
		return this.erzeuger;
	}

	public void setErzeuger(String erzeuger) {
		this.erzeuger = erzeuger;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "k_datum", nullable = false, length = 35)
	public Date getKDatum() {
		return this.KDatum;
	}

	public void setKDatum(Date KDatum) {
		this.KDatum = KDatum;
	}

	@Column(name = "k_text", length = 1024)
	public String getKText() {
		return this.KText;
	}

	public void setKText(String KText) {
		this.KText = KText;
	}

}
