package de.intevation.lada.model;

// Generated 21.05.2013 16:58:30 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LMesswertId generated by hbm2java
 */
@Embeddable
public class LMesswertId implements java.io.Serializable {

	private String probeId;
	private Integer messungsId;
	private int messgroesseId;

	public LMesswertId() {
	}

	public LMesswertId(String probeId, Integer messungsId, int messgroesseId) {
		this.probeId = probeId;
		this.messungsId = messungsId;
		this.messgroesseId = messgroesseId;
	}

	@Column(name = "probe_id", nullable = false, length = 20)
	public String getProbeId() {
		return this.probeId;
	}

	public void setProbeId(String probeId) {
		this.probeId = probeId;
	}

	@Column(name = "messungs_id", nullable = false)
	public Integer getMessungsId() {
		return this.messungsId;
	}

	public void setMessungsId(Integer messungsId) {
		this.messungsId = messungsId;
	}

	@Column(name = "messgroesse_id", nullable = false)
	public int getMessgroesseId() {
		return this.messgroesseId;
	}

	public void setMessgroesseId(int messgroesseId) {
		this.messgroesseId = messgroesseId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LMesswertId))
			return false;
		LMesswertId castOther = (LMesswertId) other;

		return ((this.getProbeId() == castOther.getProbeId()) || (this
				.getProbeId() != null && castOther.getProbeId() != null && this
				.getProbeId().equals(castOther.getProbeId())))
				&& (this.getMessungsId() == castOther.getMessungsId())
				&& (this.getMessgroesseId() == castOther.getMessgroesseId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getProbeId() == null ? 0 : this.getProbeId().hashCode());
		result = 37 * result + this.getMessungsId();
		result = 37 * result + this.getMessgroesseId();
		return result;
	}

}
