package de.intevation.lada.model;

// Generated 21.05.2013 16:58:30 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LOrt generated by hbm2java
 */
@Entity
@Table(name = "l_ort", schema = "public")
@SequenceGenerator(name = "LORT_ID_STORE", sequenceName = "l_ort_id_seq")
public class LOrt implements java.io.Serializable {

	private int POrtId;
	private int ortId;
	private String probeId;
	private String ortsTyp;
	private String ortszusatztext;
	private Date letzteAenderung;

	public LOrt() {
	}

	public LOrt(int POrtId, int ortId, String probeId) {
		this.POrtId = POrtId;
		this.ortId = ortId;
		this.probeId = probeId;
	}

	public LOrt(int POrtId, int ortId, String probeId, String ortsTyp,
			String ortszusatztext, Date letzteAenderung) {
		this.POrtId = POrtId;
		this.ortId = ortId;
		this.probeId = probeId;
		this.ortsTyp = ortsTyp;
		this.ortszusatztext = ortszusatztext;
		this.letzteAenderung = letzteAenderung;
	}

	@Id
	@Column(name = "p_ort_id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "LORT_ID_STORE")
	public int getPOrtId() {
		return this.POrtId;
	}

	public void setPOrtId(int POrtId) {
		this.POrtId = POrtId;
	}

	@Column(name = "ort_id", nullable = false)
	public int getOrtId() {
		return this.ortId;
	}

	public void setOrtId(int ortId) {
		this.ortId = ortId;
	}

	@Column(name = "probe_id", nullable = false)
	public String getProbeId() {
		return this.probeId;
	}

	public void setProbeId(String probeId) {
		this.probeId = probeId;
	}

	@Column(name = "orts_typ", length = 1)
	public String getOrtsTyp() {
		return this.ortsTyp;
	}

	public void setOrtsTyp(String ortsTyp) {
		this.ortsTyp = ortsTyp;
	}

	@Column(name = "ortszusatztext", length = 100)
	public String getOrtszusatztext() {
		return this.ortszusatztext;
	}

	public void setOrtszusatztext(String ortszusatztext) {
		this.ortszusatztext = ortszusatztext;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "letzte_aenderung", length = 29)
	public Date getLetzteAenderung() {
		return this.letzteAenderung;
	}

	public void setLetzteAenderung(Date letzteAenderung) {
		this.letzteAenderung = letzteAenderung;
	}

}
