package de.intevation.lada.model;

// Generated 21.05.2013 16:58:30 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LZusatzWertId generated by hbm2java
 */
@Embeddable
public class LZusatzWertId implements java.io.Serializable {

	private String probeId;
	private String pzsId;

	public LZusatzWertId() {
	}

	public LZusatzWertId(String probeId, String pzsId) {
		this.probeId = probeId;
		this.pzsId = pzsId;
	}

	@Column(name = "probe_id", nullable = false, length = 20)
	public String getProbeId() {
		return this.probeId;
	}

	public void setProbeId(String probeId) {
		this.probeId = probeId;
	}

	@Column(name = "pzs_id", nullable = false, length = 3)
	public String getPzsId() {
		return this.pzsId;
	}

	public void setPzsId(String pzsId) {
		this.pzsId = pzsId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LZusatzWertId))
			return false;
		LZusatzWertId castOther = (LZusatzWertId) other;

		return ((this.getProbeId() == castOther.getProbeId()) || (this
				.getProbeId() != null && castOther.getProbeId() != null && this
				.getProbeId().equals(castOther.getProbeId())))
				&& ((this.getPzsId() == castOther.getPzsId()) || (this
						.getPzsId() != null && castOther.getPzsId() != null && this
						.getPzsId().equals(castOther.getPzsId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getProbeId() == null ? 0 : this.getProbeId().hashCode());
		result = 37 * result
				+ (getPzsId() == null ? 0 : this.getPzsId().hashCode());
		return result;
	}

}
