package de.intevation.lada.model;

// Generated 21.05.2013 16:58:30 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ort generated by hbm2java
 */
@Entity
@Table(name = "ort", schema = "public")
public class Ort implements java.io.Serializable {

	private int ortId;
	private String OTyp;
	private String bezeichnung;
	private String beschreibung;
	private Character unscharf;
	private String nutsCode;
	private String koordXExtern;
	private String koordYExtern;
	private Float hoeheLand;
	private Date letzteAenderung;
	private Double latitude;
	private Double longitude;
    private int staatId;
    private String gemId;

	public Ort() {
	}

	public Ort(int ortId) {
		this.ortId = ortId;
	}

	public Ort(int ortId,  String OTyp, String bezeichnung,
			String beschreibung, Character unscharf, String nutsCode,
			String koordXExtern, String koordYExtern, Float hoeheLand,
			Date letzteAenderung, Double latitude, Double longitude,
            int staatId, String gemId) {
		this.ortId = ortId;
		this.OTyp = OTyp;
		this.bezeichnung = bezeichnung;
		this.beschreibung = beschreibung;
		this.unscharf = unscharf;
		this.nutsCode = nutsCode;
		this.koordXExtern = koordXExtern;
		this.koordYExtern = koordYExtern;
		this.hoeheLand = hoeheLand;
		this.letzteAenderung = letzteAenderung;
		this.latitude = latitude;
		this.longitude = longitude;
        this.staatId = staatId;
        this.gemId = gemId;
	}

	@Id
	@Column(name = "ort_id", unique = true, nullable = false)
	@SequenceGenerator(name = "ORT_ID_STORE", sequenceName = "ort_ort_id_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "ORT_ID_STORE")
	public int getOrtId() {
		return this.ortId;
	}

	public void setOrtId(int ortId) {
		this.ortId = ortId;
	}

	@Column(name = "o_typ", length = 1)
	public String getOTyp() {
		return this.OTyp;
	}

	public void setOTyp(String OTyp) {
		this.OTyp = OTyp;
	}

	@Column(name = "bezeichnung", length = 10)
	public String getBezeichnung() {
		return this.bezeichnung;
	}

	public void setBezeichnung(String bezeichnung) {
		this.bezeichnung = bezeichnung;
	}

	@Column(name = "beschreibung", length = 100)
	public String getBeschreibung() {
		return this.beschreibung;
	}

	public void setBeschreibung(String beschreibung) {
		this.beschreibung = beschreibung;
	}

	@Column(name = "unscharf", length = 1)
	public Character getUnscharf() {
		return this.unscharf;
	}

	public void setUnscharf(Character unscharf) {
		this.unscharf = unscharf;
	}

	@Column(name = "nuts_code", length = 10)
	public String getNutsCode() {
		return this.nutsCode;
	}

	public void setNutsCode(String nutsCode) {
		this.nutsCode = nutsCode;
	}

	@Column(name = "koord_x_extern", length = 22)
	public String getKoordXExtern() {
		return this.koordXExtern;
	}

	public void setKoordXExtern(String koordXExtern) {
		this.koordXExtern = koordXExtern;
	}

	@Column(name = "koord_y_extern", length = 22)
	public String getKoordYExtern() {
		return this.koordYExtern;
	}

	public void setKoordYExtern(String koordYExtern) {
		this.koordYExtern = koordYExtern;
	}

	@Column(name = "hoehe_land", precision = 8, scale = 8)
	public Float getHoeheLand() {
		return this.hoeheLand;
	}

	public void setHoeheLand(Float hoeheLand) {
		this.hoeheLand = hoeheLand;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "letzte_aenderung", length = 29)
	public Date getLetzteAenderung() {
		return this.letzteAenderung;
	}

	public void setLetzteAenderung(Date letzteAenderung) {
		this.letzteAenderung = letzteAenderung;
	}

	@Column(name = "latitude", precision = 17, scale = 17)
	public Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	@Column(name = "longitude", precision = 17, scale = 17)
	public Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

    @Column(name = "gem_id")
    public String getGemId() {
        return this.gemId;
    }

    public void setGemId(String gemId) {
        this.gemId= gemId;
    }

    @Column(name = "staat_id")
    public int getStaatId() {
        return this.staatId;
    }

    public void setStaatId(int staatId) {
        this.staatId= staatId;
    }
}
