package de.intevation.lada.model;

// Generated 21.05.2013 16:58:30 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SKoordinatenArt generated by hbm2java
 */
@Entity
@Table(name = "s_koordinaten_art", schema = "public")
public class SKoordinatenArt implements java.io.Serializable {

	private short kdaId;
	private String koordinatenart;
	private String idfGeoKey;

	public SKoordinatenArt() {
	}

	public SKoordinatenArt(short kdaId) {
		this.kdaId = kdaId;
	}

	public SKoordinatenArt(short kdaId, String koordinatenart,
			String idfGeoKey) {
		this.kdaId = kdaId;
		this.koordinatenart = koordinatenart;
		this.idfGeoKey = idfGeoKey;
	}

	@Id
	@Column(name = "kda_id", unique = true, nullable = false)
	public short getKdaId() {
		return this.kdaId;
	}

	public void setKdaId(short kdaId) {
		this.kdaId = kdaId;
	}

	@Column(name = "koordinatenart", length = 50)
	public String getKoordinatenart() {
		return this.koordinatenart;
	}

	public void setKoordinatenart(String koordinatenart) {
		this.koordinatenart = koordinatenart;
	}

	@Column(name = "idf_geo_key", length = 1)
	public String getIdfGeoKey() {
		return this.idfGeoKey;
	}

	public void setIdfGeoKey(String idfGeoKey) {
		this.idfGeoKey = idfGeoKey;
	}

}
