/* Copyright (C) 2013 by Bundesamt fuer Strahlenschutz
 * Software engineering by Intevation GmbH
 *
 * This file is Free Software under the GNU GPL (v>=3) 
 * and comes with ABSOLUTELY NO WARRANTY! Check out 
 * the documentation coming with IMIS-Labordaten-Application for details. 
 */
package de.intevation.lada.model;

// Generated 24.06.2013 16:31:53 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * SMessMethode generated by hbm2java
 */
@Entity
@Table(name = "s_mess_methode"
    , schema = "public")
public class SMessMethode
implements java.io.Serializable
{

    private String        mmtId;
    private String        beschreibung;
    private String        messmethode;

    public SMessMethode() {
    }

    public SMessMethode(String mmtId) {
        this.mmtId = mmtId;
    }

    public SMessMethode(
        String mmtId,
        String beschreibung,
        String messmethode) {
        this.mmtId = mmtId;
        this.beschreibung = beschreibung;
        this.messmethode = messmethode;
    }

    @Id
    @Column(name = "mmt_id", unique = true, nullable = false, length = 2)
    public String getMmtId() {
        return this.mmtId;
    }

    public void setMmtId(String mmtId) {
        this.mmtId = mmtId;
    }

    @Column(name = "beschreibung", length = 300)
    public String getBeschreibung() {
        return this.beschreibung;
    }

    public void setBeschreibung(String beschreibung) {
        this.beschreibung = beschreibung;
    }

    @Column(name = "messmethode", length = 50)
    public String getMessmethode() {
        return this.messmethode;
    }

    public void setMessmethode(String messmethode) {
        this.messmethode = messmethode;
    }
}
