package de.intevation.lada.model;

// Generated 24.06.2013 16:31:53 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;


/**
 * SMessMethode generated by hbm2java
 */
@Entity
@Table(name = "s_mess_methode"
    , schema = "public")
public class SMessMethode
implements java.io.Serializable
{

    private String        mmtId;
    private String        beschreibung;
    private String        messmethhode;

    public SMessMethode() {
    }

    public SMessMethode(String mmtId) {
        this.mmtId = mmtId;
    }

    public SMessMethode(
        String mmtId,
        String beschreibung,
        String messmethhode) {
        this.mmtId = mmtId;
        this.beschreibung = beschreibung;
        this.messmethhode = messmethhode;
    }

    @Id
    @Column(name = "mmt_id", unique = true, nullable = false, length = 2)
    public String getMmtId() {
        return this.mmtId;
    }

    public void setMmtId(String mmtId) {
        this.mmtId = mmtId;
    }

    @Column(name = "beschreibung", length = 300)
    public String getBeschreibung() {
        return this.beschreibung;
    }

    public void setBeschreibung(String beschreibung) {
        this.beschreibung = beschreibung;
    }

    @Column(name = "messmethhode", length = 50)
    public String getMessmethhode() {
        return this.messmethhode;
    }

    public void setMessmethhode(String messmethhode) {
        this.messmethhode = messmethhode;
    }
}
