package de.intevation.lada.model;

// Generated 21.05.2013 16:58:30 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SMessEinheit generated by hbm2java
 */
@Entity
@Table(name = "s_mess_einheit", schema = "public")
public class SMessEinheit implements java.io.Serializable {

	private short mehId;
	private String beschreibung;
	private String einheit;
	private String eudfMesseinheitId;
	private Long umrechnungsFaktorEudf;

	public SMessEinheit() {
	}

	public SMessEinheit(short mehId) {
		this.mehId = mehId;
	}

	public SMessEinheit(short mehId, String beschreibung, String einheit,
			String eudfMesseinheitId, Long umrechnungsFaktorEudf) {
		this.mehId = mehId;
		this.beschreibung = beschreibung;
		this.einheit = einheit;
		this.eudfMesseinheitId = eudfMesseinheitId;
		this.umrechnungsFaktorEudf = umrechnungsFaktorEudf;
	}

	@Id
	@Column(name = "meh_id", unique = true, nullable = false)
	public short getMehId() {
		return this.mehId;
	}

	public void setMehId(short mehId) {
		this.mehId = mehId;
	}

	@Column(name = "beschreibung", length = 50)
	public String getBeschreibung() {
		return this.beschreibung;
	}

	public void setBeschreibung(String beschreibung) {
		this.beschreibung = beschreibung;
	}

	@Column(name = "einheit", length = 12)
	public String getEinheit() {
		return this.einheit;
	}

	public void setEinheit(String einheit) {
		this.einheit = einheit;
	}

	@Column(name = "eudf_messeinheit_id", length = 8)
	public String getEudfMesseinheitId() {
		return this.eudfMesseinheitId;
	}

	public void setEudfMesseinheitId(String eudfMesseinheitId) {
		this.eudfMesseinheitId = eudfMesseinheitId;
	}

	@Column(name = "umrechnungs_faktor_eudf")
	public Long getUmrechnungsFaktorEudf() {
		return this.umrechnungsFaktorEudf;
	}

	public void setUmrechnungsFaktorEudf(Long umrechnungsFaktorEudf) {
		this.umrechnungsFaktorEudf = umrechnungsFaktorEudf;
	}
}
