package de.intevation.lada.model;

// Generated 21.05.2013 16:58:30 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SProbenart generated by hbm2java
 */
@Entity
@Table(name = "s_probenart", schema = "public")
public class SProbenart implements java.io.Serializable {

	private short probenartId;
	private String beschreibung;
	private String probenart;
	private String probenartEudfId;

	public SProbenart() {
	}

	public SProbenart(short probenartId, String probenart,
			String probenartEudfId) {
		this.probenartId = probenartId;
		this.probenart = probenart;
		this.probenartEudfId = probenartEudfId;
	}

	public SProbenart(short probenartId, String beschreibung, String probenart,
			String probenartEudfId) {
		this.probenartId = probenartId;
		this.beschreibung = beschreibung;
		this.probenart = probenart;
		this.probenartEudfId = probenartEudfId;
	}

	@Id
	@Column(name = "probenart_id", unique = true, nullable = false)
	public short getProbenartId() {
		return this.probenartId;
	}

	public void setProbenartId(short probenartId) {
		this.probenartId = probenartId;
	}

	@Column(name = "beschreibung", length = 30)
	public String getBeschreibung() {
		return this.beschreibung;
	}

	public void setBeschreibung(String beschreibung) {
		this.beschreibung = beschreibung;
	}

	@Column(name = "probenart", nullable = false, length = 5)
	public String getProbenart() {
		return this.probenart;
	}

	public void setProbenart(String probenart) {
		this.probenart = probenart;
	}

	@Column(name = "probenart_eudf_id", nullable = false, length = 1)
	public String getProbenartEudfId() {
		return this.probenartEudfId;
	}

	public void setProbenartEudfId(String probenartEudfId) {
		this.probenartEudfId = probenartEudfId;
	}
}
