package de.intevation.lada.model;

// Generated 21.05.2013 16:58:30 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SStaat generated by hbm2java
 */
@Entity
@Table(name = "s_staat", schema = "public")
public class SStaat implements java.io.Serializable {

	private short staatId;
	private SKoordinatenArt SKoordinatenArt;
	private String staat;
	private short hklId;
	private String staatIso;
	private String staatKurz;
	private Character eu;
	private String koordXExtern;
	private String koordYExtern;

	public SStaat() {
	}

	public SStaat(short staatId, String staat, short hklId, String staatIso) {
		this.staatId = staatId;
		this.staat = staat;
		this.hklId = hklId;
		this.staatIso = staatIso;
	}

	public SStaat(short staatId, SKoordinatenArt SKoordinatenArt, String staat,
			short hklId, String staatIso, String staatKurz, Character eu,
			String koordXExtern, String koordYExtern) {
		this.staatId = staatId;
		this.SKoordinatenArt = SKoordinatenArt;
		this.staat = staat;
		this.hklId = hklId;
		this.staatIso = staatIso;
		this.staatKurz = staatKurz;
		this.eu = eu;
		this.koordXExtern = koordXExtern;
		this.koordYExtern = koordYExtern;
	}

	@Id
	@Column(name = "staat_id", unique = true, nullable = false)
	public short getStaatId() {
		return this.staatId;
	}

	public void setStaatId(short staatId) {
		this.staatId = staatId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "kda_id")
	public SKoordinatenArt getSKoordinatenArt() {
		return this.SKoordinatenArt;
	}

	public void setSKoordinatenArt(SKoordinatenArt SKoordinatenArt) {
		this.SKoordinatenArt = SKoordinatenArt;
	}

	@Column(name = "staat", nullable = false, length = 50)
	public String getStaat() {
		return this.staat;
	}

	public void setStaat(String staat) {
		this.staat = staat;
	}

	@Column(name = "hkl_id", nullable = false)
	public short getHklId() {
		return this.hklId;
	}

	public void setHklId(short hklId) {
		this.hklId = hklId;
	}

	@Column(name = "staat_iso", nullable = false, length = 2)
	public String getStaatIso() {
		return this.staatIso;
	}

	public void setStaatIso(String staatIso) {
		this.staatIso = staatIso;
	}

	@Column(name = "staat_kurz", length = 5)
	public String getStaatKurz() {
		return this.staatKurz;
	}

	public void setStaatKurz(String staatKurz) {
		this.staatKurz = staatKurz;
	}

	@Column(name = "eu", length = 1)
	public Character getEu() {
		return this.eu;
	}

	public void setEu(Character eu) {
		this.eu = eu;
	}

	@Column(name = "koord_x_extern", length = 22)
	public String getKoordXExtern() {
		return this.koordXExtern;
	}

	public void setKoordXExtern(String koordXExtern) {
		this.koordXExtern = koordXExtern;
	}

	@Column(name = "koord_y_extern", length = 22)
	public String getKoordYExtern() {
		return this.koordYExtern;
	}

	public void setKoordYExtern(String koordYExtern) {
		this.koordYExtern = koordYExtern;
	}

}
