package de.intevation.lada.model;

// Generated 21.05.2013 16:58:30 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * SUmwelt generated by hbm2java
 */
@Entity
@Table(name = "s_umwelt", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "umwelt_bereich"))
public class SUmwelt implements java.io.Serializable {

	private String umwId;
	private SMessEinheit SMessEinheit;
	private String beschreibung;
	private String umweltBereich;

	public SUmwelt() {
	}

	public SUmwelt(String umwId, String umweltBereich) {
		this.umwId = umwId;
		this.umweltBereich = umweltBereich;
	}

	public SUmwelt(String umwId, SMessEinheit SMessEinheit,
			String beschreibung, String umweltBereich) {
		this.umwId = umwId;
		this.SMessEinheit = SMessEinheit;
		this.beschreibung = beschreibung;
		this.umweltBereich = umweltBereich;
	}

	@Id
	@Column(name = "umw_id", unique = true, nullable = false, length = 3)
	public String getUmwId() {
		return this.umwId;
	}

	public void setUmwId(String umwId) {
		this.umwId = umwId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "meh_id")
	public SMessEinheit getSMessEinheit() {
		return this.SMessEinheit;
	}

	public void setSMessEinheit(SMessEinheit SMessEinheit) {
		this.SMessEinheit = SMessEinheit;
	}

	@Column(name = "beschreibung", length = 300)
	public String getBeschreibung() {
		return this.beschreibung;
	}

	public void setBeschreibung(String beschreibung) {
		this.beschreibung = beschreibung;
	}

	@Column(name = "umwelt_bereich", unique = true, nullable = false, length = 80)
	public String getUmweltBereich() {
		return this.umweltBereich;
	}

	public void setUmweltBereich(String umweltBereich) {
		this.umweltBereich = umweltBereich;
	}
}
