/* Copyright (C) 2013 by Bundesamt fuer Strahlenschutz
 * Software engineering by Intevation GmbH
 *
 * This file is Free Software under the GNU GPL (v>=3) 
 * and comes with ABSOLUTELY NO WARRANTY! Check out 
 * the documentation coming with IMIS-Labordaten-Application for details. 
 */
package de.intevation.lada.model;

// Generated 21.05.2013 16:58:30 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SVerwaltungseinheit generated by hbm2java
 */
@Entity
@Table(name = "s_verwaltungseinheit", schema = "public")
public class SVerwaltungseinheit implements java.io.Serializable {

	private String gemId;
	private String bundesland;
	private Short kdaId;
	private String kreis;
	private String nuts;
	private String regbezirk;
	private String bezeichnung;
	private char isBundesland;
	private char isGemeinde;
	private char isLandkreis;
	private char isRegbezirk;
	private String koordXExtern;
	private String koordYExtern;
	private String plz;
	private Double longitude;
	private Double latitude;

	public SVerwaltungseinheit() {
	}

	public SVerwaltungseinheit(String gemId, String bundesland,
			String bezeichnung, char isBundesland, char isGemeinde,
			char isLandkreis, char isRegbezirk) {
		this.gemId = gemId;
		this.bundesland = bundesland;
		this.bezeichnung = bezeichnung;
		this.isBundesland = isBundesland;
		this.isGemeinde = isGemeinde;
		this.isLandkreis = isLandkreis;
		this.isRegbezirk = isRegbezirk;
	}

	public SVerwaltungseinheit(String gemId, String bundesland, Short kdaId,
			String kreis, String nuts, String regbezirk, String bezeichnung,
			char isBundesland, char isGemeinde, char isLandkreis,
			char isRegbezirk, String koordXExtern,
			String koordYExtern, String plz,
			Double longitude, Double latitude) {
		this.gemId = gemId;
		this.bundesland = bundesland;
		this.kdaId = kdaId;
		this.kreis = kreis;
		this.nuts = nuts;
		this.regbezirk = regbezirk;
		this.bezeichnung = bezeichnung;
		this.isBundesland = isBundesland;
		this.isGemeinde = isGemeinde;
		this.isLandkreis = isLandkreis;
		this.isRegbezirk = isRegbezirk;
		this.koordXExtern = koordXExtern;
		this.koordYExtern = koordYExtern;
		this.plz = plz;
		this.longitude = longitude;
		this.latitude = latitude;
	}

	@Id
	@Column(name = "gem_id", unique = true, nullable = false, length = 8)
	public String getGemId() {
		return this.gemId;
	}

	public void setGemId(String gemId) {
		this.gemId = gemId;
	}

	@Column(name = "bundesland", nullable = false, length = 8)
	public String getBundesland() {
		return this.bundesland;
	}

	public void setBundesland(String bundesland) {
		this.bundesland = bundesland;
	}

	@Column(name = "kda_id")
	public Short getKdaId() {
		return this.kdaId;
	}

	public void setKdaId(Short kdaId) {
		this.kdaId = kdaId;
	}

	@Column(name = "kreis", length = 8)
	public String getKreis() {
		return this.kreis;
	}

	public void setKreis(String kreis) {
		this.kreis = kreis;
	}

	@Column(name = "nuts", length = 10)
	public String getNuts() {
		return this.nuts;
	}

	public void setNuts(String nuts) {
		this.nuts = nuts;
	}

	@Column(name = "regbezirk", length = 8)
	public String getRegbezirk() {
		return this.regbezirk;
	}

	public void setRegbezirk(String regbezirk) {
		this.regbezirk = regbezirk;
	}

	@Column(name = "bezeichnung", nullable = false, length = 80)
	public String getBezeichnung() {
		return this.bezeichnung;
	}

	public void setBezeichnung(String bezeichnung) {
		this.bezeichnung = bezeichnung;
	}

	@Column(name = "is_bundesland", nullable = false, length = 1)
	public char getIsBundesland() {
		return this.isBundesland;
	}

	public void setIsBundesland(char isBundesland) {
		this.isBundesland = isBundesland;
	}

	@Column(name = "is_gemeinde", nullable = false, length = 1)
	public char getIsGemeinde() {
		return this.isGemeinde;
	}

	public void setIsGemeinde(char isGemeinde) {
		this.isGemeinde = isGemeinde;
	}

	@Column(name = "is_landkreis", nullable = false, length = 1)
	public char getIsLandkreis() {
		return this.isLandkreis;
	}

	public void setIsLandkreis(char isLandkreis) {
		this.isLandkreis = isLandkreis;
	}

	@Column(name = "is_regbezirk", nullable = false, length = 1)
	public char getIsRegbezirk() {
		return this.isRegbezirk;
	}

	public void setIsRegbezirk(char isRegbezirk) {
		this.isRegbezirk = isRegbezirk;
	}

	@Column(name = "koord_x_extern", length = 22)
	public String getKoordXExtern() {
		return this.koordXExtern;
	}

	public void setKoordXExtern(String koordXExtern) {
		this.koordXExtern = koordXExtern;
	}

	@Column(name = "koord_y_extern", length = 22)
	public String getKoordYExtern() {
		return this.koordYExtern;
	}

	public void setKoordYExtern(String koordYExtern) {
		this.koordYExtern = koordYExtern;
	}

	@Column(name = "plz", length = 6)
	public String getPlz() {
		return this.plz;
	}

	public void setPlz(String plz) {
		this.plz = plz;
	}

	@Column(name = "longitude", precision = 17, scale = 17)
	public Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	@Column(name = "latitude", precision = 17, scale = 17)
	public Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

}
