#!/bin/sh

# This script installs NX server using FreeNX on a CentOS machine.
#
# Running the script:
# $ sudo chmod +x nx_install
# $ sudo ./nx_install
#
# Author Boriss Redkins.

# (optional)
#USER=user
#PASSWORD=password

# install nx
sudo yum install nx freenx -y

# backup configuration
sudo cp /etc/nxserver/node.conf.sample /etc/nxserver/node.conf 

# enable password authentication
sudo sed -i 's/#ENABLE_PASSDB_AUTHENTICATION="0"/ENABLE_PASSDB_AUTHENTICATION="1"/g' /etc/nxserver/node.conf

# (optional)
# add nx user 
#sudo nxserver --adduser $USER --system -administrator

# (optional)
# add nx user password 
#sudo nxserver --passwd $USER <<EOF
#$PASSWORD
#EOF

# display the key to be used in the nx client configuration
sudo cat /etc/nxserver/client.id_dsa.key

