#!/bin/sh

# This script removes NX server using FreeNX from a CentOS machine.
#
# Running the script:
# modify the USER variable
# $ sudo chmod +x nx_remove
# $ sudo ./nx_remove
#
# Author Boriss Redkins.

USER=user

# remove nx
sudo yum remove nx freenx -y

# remove nx directory
sudo rm -r /etc/nxserver
echo INFO: nx directory deleted

# remove Public key
sudo rm -r /home/$USER/.ssh/authorized_keys*
echo INFO: Public key deleted

