<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:shl="java:net.sf.xslthl.ConnectorSaxon6"
	xmlns:xhl="http://net.sf.xslthl/XalanConnector" xmlns:xalan="http://xml.apache.org/xalan" xmlns:xslthl="http://xslthl.sf.net"
	extension-element-prefixes="shl xhl xalan xslthl">
	<xsl:output indent="no" method="html" version="1.0" doctype-system="http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"
		doctype-public="-//W3C//DTD XHTML 1.0 Strict//EN" />
		
		<!-- this parameter is used to set the location of the filename -->
	<xsl:param name="xslthl.config" />
	
	<!-- this construction is needed to have the saxon and xalan connectors working alongside eachother -->
	<xalan:component prefix="xhl" functions="highlight">
		<xalan:script lang="javaclass" src="xalan://net.sf.xslthl.XalanConnector" />
	</xalan:component>
	
	<!-- start of the stylesheet -->
	<xsl:template match="/">
		<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
			<head>
				<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
				<title>Example syntax highlighting with xslthl</title>
				<style><![CDATA[
BODY {
	color: black;
	background: white;
	padding: 0.5em;
}				

PRE {
	background: #ffe;
	border: 1px solid #eed;
}

H1 {
	border-left: 5px solid #aaf;
	padding-left: 0.25em;
	margin-left: -0.5em;
	background: #eef;
}
				]]></style>
			</head>
			<body>
				<xsl:apply-templates />
				<hr />
				<address>
					Generated by:
					<xsl:value-of select="system-property('xsl:vendor')" />
					(
					<xsl:value-of select="system-property('xsl:vendor-url')" />
					) - Xslt version:
					<xsl:value-of select="system-property('xsl:version')" />
				</address>
			</body>
		</html>
	</xsl:template>
	<xsl:template match="para">
		<p>
			<xsl:apply-templates />
		</p>
	</xsl:template>
	<xsl:template match="header">
		<h1>
			<xsl:apply-templates />
		</h1>
	</xsl:template>
	<xsl:template match="bold">
		<b>
			<xsl:apply-templates />
		</b>
	</xsl:template>
	<xsl:template match="underline">
		<u>
			<xsl:apply-templates />
		</u>
	</xsl:template>
	<xsl:template match="code">
		<pre>
			<xsl:call-template name="syntax-highlight">
				<xsl:with-param name="language">
					<xsl:value-of select="@language" />
				</xsl:with-param>
				<xsl:with-param name="source" select="." />
			</xsl:call-template>
		</pre>
	</xsl:template>
	
	<!-- highlighting of the xslthl tags -->
	<xsl:template match="xslthl:keyword">
		<b>
			<xsl:value-of select="." />
		</b>
	</xsl:template>
	<xsl:template match="xslthl:string">
		<span style="color: blue;">
			<xsl:value-of select="." />
		</span>
	</xsl:template>
	<xsl:template match="xslthl:number">
		<span style="color: blue;">
			<xsl:value-of select="." />
		</span>
	</xsl:template>
	<xsl:template match="xslthl:comment">
		<span style="color: green; font-style: italic;">
			<xsl:value-of select="." />
		</span>
	</xsl:template>
	<xsl:template match="xslthl:directive">
		<span style="color: maroon;">
			<xsl:value-of select="." />
		</span>
	</xsl:template>
	<xsl:template match="xslthl:annotation">
		<span style="color: gray; font-style: italic;">
			<xsl:value-of select="." />
		</span>
	</xsl:template>

	<!-- default XML styles -->
	<xsl:template match="xslthl:tag">
		<span style="color: teal;">
			<xsl:value-of select="." />
		</span>
	</xsl:template>
	<xsl:template match="xslthl:attribute">
		<span style="color: purple;">
			<xsl:value-of select="." />
		</span>
	</xsl:template>
	<xsl:template match="xslthl:value">
		<span style="color: blue;">
			<xsl:value-of select="." />
		</span>
	</xsl:template>
	
	<!-- This template will perform the actual highlighting -->
	<xsl:template name="syntax-highlight">
		<xsl:param name="language" />
		<xsl:param name="source" />
		<xsl:choose>
			<xsl:when test="function-available('shl:highlight')">
				<xsl:variable name="highlighted" select="shl:highlight($language, $source, $xslthl.config)" />
				<xsl:apply-templates select="$highlighted" />
			</xsl:when>
			<xsl:when test="function-available('xhl:highlight')">
				<xsl:variable name="highlighted" select="xhl:highlight($language, $source, $xslthl.config)" />
				<xsl:apply-templates select="$highlighted" />
			</xsl:when>
			<xsl:otherwise>
				<div style="border: 2px solid red; background: white; font-family: sans-serif; padding: 0.5em; font-size: 2em;">No syntax highligter available</div>
				<xsl:apply-templates select="$source/*|$source/text()" />
			</xsl:otherwise>
		</xsl:choose>
	</xsl:template>
</xsl:stylesheet>