#!/bin/sh
#
# The Apache Software License, Version 1.1
#
#
# Copyright (c) 1999 The Apache Software Foundation.  All rights 
# reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer. 
#
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in
#    the documentation and/or other materials provided with the
#    distribution.
#
# 3. The end-user documentation included with the redistribution,
#    if any, must include the following acknowledgment:  
#       "This product includes software developed by the
#        Apache Software Foundation (http://www.apache.org/)."
#    Alternately, this acknowledgment may appear in the software itself,
#    if and wherever such third-party acknowledgments normally appear.
#
# 4. The names "<WebSig>" and "Apache Software Foundation" must
#    not be used to endorse or promote products derived from this
#    software without prior written permission. For written 
#    permission, please contact apache@apache.org.
#
# 5. Products derived from this software may not be called "Apache",
#    nor may "Apache" appear in their name, without prior written
#    permission of the Apache Software Foundation.
#
# THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESSED OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
# OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED.  IN NO EVENT SHALL THE APACHE SOFTWARE FOUNDATION OR
# ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF
# USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
# OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
# ====================================================================
#
# This software consists of voluntary contributions made by many
# individuals on behalf of the Apache Software Foundation and was
# originally based on software copyright (c) 2001, Institute for
# Data Communications Systems, <http://www.nue.et-inf.uni-siegen.de/>.
# The development of this software was partly funded by the European 
# Commission in the <WebSig> project in the ISIS Programme. 
# For more information on the Apache Software Foundation, please see
# <http://www.apache.org/>.

# A simple test script
# Runs through the Merlin Interop samples and checks they are OK

# There can be a number of failures.
#
# 1. the file http://xmldsig.pothole.com/xml-stylesheet.txt no
#    longer exists.  I have it on a test http server to make these
#    tests work.
# 2. If you are not online to the Internet, the checks for documents
#    at www.w3.org will also fail.

if [ "c$XSECCROOT" = "c" ]; then
	echo Set XSECCROOT to base of c distribution before running
	exit 1
fi

DDIR=${XSECCROOT}/data
CHECKSIG=${XSECCROOT}/bin/checksig
CHECKSIG_ARGS="-x"

FAILURE_COUNT=0
PASS_COUNT=0

testSig() {

	$CHECKSIG $CHECKSIG_ARGS $1 $2 $3 $4 $5 $6 $7 $8 $9
	if [ $? != 0 ]; then
		echo $1 failed
		FAILURE_COUNT=$(( $FAILURE_COUNT + 1))
	else
		PASS_COUNT=$(( $PASS_COUNT + 1))
	fi
}


# IXSIL Examples

echo Running IXSIL examples

testSig -a $DDIR/at/iaik/ixsil/coreFeatures/signatures/anonymousReferenceSignature.xml
testSig $DDIR/at/iaik/ixsil/coreFeatures/signatures/manifestSignature.xml

# will fail if no network

testSig $DDIR/at/iaik/ixsil/coreFeatures/signatures/signatureTypesSignature.xml
testSig $DDIR/at/iaik/ixsil/signatureAlgorithms/signatures/dSASignature.xml
testSig -h secret $DDIR/at/iaik/ixsil/signatureAlgorithms/signatures/hMACShortSignature.xml
testSig -h secret $DDIR/at/iaik/ixsil/signatureAlgorithms/signatures/hMACSignature.xml
testSig $DDIR/at/iaik/ixsil/signatureAlgorithms/signatures/rSASignature.xml

testSig $DDIR/at/iaik/ixsil/transforms/signatures/base64DecodeSignature.xml
testSig $DDIR/at/iaik/ixsil/transforms/signatures/c14nSignature.xml
testSig $DDIR/at/iaik/ixsil/transforms/signatures/envelopedSignatureSignature.xml
testSig $DDIR/at/iaik/ixsil/transforms/signatures/xPathSignature.xml



testSig $DDIR/com/rsasecurity/bdournaee/certj201_enveloped.xml
testSig $DDIR/com/rsasecurity/bdournaee/certj201_enveloping.xml
testSig $DDIR/ie/baltimore/merlin-examples/ec-merlin-iaikTests-two/signature.xml
testSig $DDIR/ie/baltimore/merlin-examples/merlin-exc-c14n-one/exc-signature.xml

testSig -i $DDIR/ie/baltimore/merlin-examples/merlin-xmldsig-eighteen/signature-keyname.xml
testSig -i $DDIR/ie/baltimore/merlin-examples/merlin-xmldsig-eighteen/signature-retrievalmethod-rawx509crt.xml
testSig -i $DDIR/ie/baltimore/merlin-examples/merlin-xmldsig-eighteen/signature-x509-crt-crl.xml
testSig $DDIR/ie/baltimore/merlin-examples/merlin-xmldsig-eighteen/signature-x509-crt.xml
testSig -i $DDIR/ie/baltimore/merlin-examples/merlin-xmldsig-eighteen/signature-x509-is.xml
testSig -i $DDIR/ie/baltimore/merlin-examples/merlin-xmldsig-eighteen/signature-x509-ski.xml
testSig -i $DDIR/ie/baltimore/merlin-examples/merlin-xmldsig-eighteen/signature-x509-sn.xml



testSig $DDIR/ie/baltimore/merlin-examples/merlin-xmldsig-fifteen/signature-enveloped-dsa.xml
testSig $DDIR/ie/baltimore/merlin-examples/merlin-xmldsig-fifteen/signature-enveloping-b64-dsa.xml
testSig $DDIR/ie/baltimore/merlin-examples/merlin-xmldsig-fifteen/signature-enveloping-dsa.xml
testSig -h secret $DDIR/ie/baltimore/merlin-examples/merlin-xmldsig-fifteen/signature-enveloping-hmac-sha1-40.xml
testSig -h secret $DDIR/ie/baltimore/merlin-examples/merlin-xmldsig-fifteen/signature-enveloping-hmac-sha1.xml
testSig $DDIR/ie/baltimore/merlin-examples/merlin-xmldsig-fifteen/signature-enveloping-rsa.xml
testSig $DDIR/ie/baltimore/merlin-examples/merlin-xmldsig-fifteen/signature-external-b64-dsa.xml
testSig $DDIR/ie/baltimore/merlin-examples/merlin-xmldsig-fifteen/signature-external-dsa.xml

# These two are removed, as this is a pre-release syntax that the library
# does not understand

# testSig $DDIR/ie/baltimore/merlin-examples/merlin-xmldsig-filter2-one/sign-xfdl.xml
# testSig $DDIR/ie/baltimore/merlin-examples/merlin-xmldsig-filter2-one/signature.xml

testSig $DDIR/ie/baltimore/merlin-examples/merlin-xmldsig-sixteen/signature.xml
testSig $DDIR/interop/c14n/Y1/exc-signature.xml

# MD5 now implemented

testSig $DDIR/interop/c14n/Y2/signature-joseph-exc.xml
testSig $DDIR/interop/c14n/Y3/signature.xml
testSig $DDIR/interop/c14n/Y4/signature.xml
testSig $DDIR/interop/c14n/Y5/signature.xml
testSig $DDIR/interop/c14n/Y5/signatureCommented.xml

# XPath Filter not implemented - should fail

testSig $DDIR/interop/xfilter2/merlin-xpath-filter2-three/sign-spec.xml
testSig $DDIR/interop/xfilter2/merlin-xpath-filter2-three/sign-xfdl.xml

# Not really tests

# testSig $DDIR/org/apache/xml/security/temp/key/dsavalue.xml
# testSig $DDIR/org/apache/xml/security/temp/key/retrieval-from-same-doc-key.xml
# testSig $DDIR/org/apache/xml/security/temp/key/retrieval-from-same-doc.xml
# testSig $DDIR/org/apache/xml/security/temp/key/signature-retrievalmethod-dsavalue.xml
# testSig $DDIR/org/apache/xml/security/temp/key/signature-retrievalmethod-x509data.xml


echo
echo
echo Signature Tests Completed
echo =========================
echo 
echo Passed = $PASS_COUNT [expected 39 if local copy of potholed, 37 if not]
echo Failed = $FAILURE_COUNT [expected 0 if local copy of pothole, 2 if not]
echo


