# Because I am old and crotchety and my fingers can't stop from running 
#	`make` commands

.PHONY: all doc tests clean

all:
	ant

init:
	ant init

doc:
	ant javadoc

tests: all unit-tests

unit-tests:
	ant tests

clean:
	ant clean
