/*
 * Copyright (c) 2014 T-Systems Multimedia Solutions GmbH
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * AppMon Server REST API
 * The AppMon Server exposes management and integration functionality via REST endpoints. This interactive documentation also acts as a REST client you can use to interact with the AppMon Server.  The HTTP status code of the response shows the result of your request. The expected response code for a successful request is documented individually per REST endpoint. Additionally the following error response codes can typically occur in our REST interface:  * **400** - Bad Request: Some request parameters are not correct. * **401** - Unauthorized: A valid authorization header (Basic Authentication) is required but is not available. * **403** - Forbidden: Execution of request is not allowed, e.g. the user has no privileges. * **404** - Not Found: Endpoint does not exist or some entities could not be found, e.g. System Profile. * **500** - Internal Server Error: See response body for details.  Additional [usage examples](https://www.dynatrace.com/support/doc/appmon70/shortlink/id_server_rest_examples) can be found in the AppMon documentation. 
 *
 * OpenAPI spec version: 2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package de.tsystems.mms.apm.performancesignature.dynatrace.model;

import com.google.gson.annotations.SerializedName;
import de.tsystems.mms.apm.performancesignature.util.PerfSigUIUtils;
import io.swagger.annotations.ApiModelProperty;
import org.kohsuke.stapler.export.Exported;
import org.kohsuke.stapler.export.ExportedBean;

import java.util.Objects;

/**
 * TestMeasure
 */

@ExportedBean
public class TestMeasure {
    @SerializedName("name")
    private final String name = null;

    @SerializedName("metricGroup")
    private final String metricGroup = null;

    @SerializedName("value")
    private final Double value = null;

    @SerializedName("unit")
    private final String unit = null;

    @SerializedName("expectedMin")
    private final Double expectedMin = null;

    @SerializedName("expectedMax")
    private final Double expectedMax = null;

    @SerializedName("numFailingOrInvalidatedRuns")
    private final Integer numFailingOrInvalidatedRuns = null;

    @SerializedName("numValidRuns")
    private final Integer numValidRuns = null;

    @SerializedName("numImprovedRuns")
    private final Integer numImprovedRuns = null;

    @SerializedName("numDegradedRuns")
    private final Integer numDegradedRuns = null;

    @SerializedName("violationPercentage")
    private final Double violationPercentage = null;

    /**
     * Get name
     *
     * @return name
     **/
    @Exported
    @ApiModelProperty()
    public String getName() {
        return name;
    }

    /**
     * Get metricGroup
     *
     * @return metricGroup
     **/
    @Exported
    @ApiModelProperty()
    public String getMetricGroup() {
        return metricGroup;
    }

    /**
     * Get value
     *
     * @return value
     **/
    @Exported
    @ApiModelProperty()
    public Double getValue() {
        return value;
    }

    /**
     * Get unit
     *
     * @return unit
     **/
    @Exported
    @ApiModelProperty()
    public String getUnit() {
        return unit;
    }

    /**
     * Get expectedMin
     *
     * @return expectedMin
     **/
    @Exported
    @ApiModelProperty()
    public Double getExpectedMin() {
        return expectedMin;
    }

    /**
     * Get expectedMax
     *
     * @return expectedMax
     **/
    @Exported
    @ApiModelProperty()
    public Double getExpectedMax() {
        return expectedMax;
    }

    /**
     * Get numFailingOrInvalidatedRuns
     *
     * @return numFailingOrInvalidatedRuns
     **/
    @Exported
    @ApiModelProperty()
    public Integer getNumFailingOrInvalidatedRuns() {
        return numFailingOrInvalidatedRuns;
    }

    /**
     * Get numValidRuns
     *
     * @return numValidRuns
     **/
    @Exported
    @ApiModelProperty()
    public Integer getNumValidRuns() {
        return numValidRuns;
    }

    /**
     * Get numImprovedRuns
     *
     * @return numImprovedRuns
     **/
    @Exported
    @ApiModelProperty()
    public Integer getNumImprovedRuns() {
        return numImprovedRuns;
    }

    /**
     * Get numDegradedRuns
     *
     * @return numDegradedRuns
     **/
    @Exported
    @ApiModelProperty()
    public Integer getNumDegradedRuns() {
        return numDegradedRuns;
    }

    /**
     * Get violationPercentage
     *
     * @return violationPercentage
     **/
    @Exported
    @ApiModelProperty()
    public Double getViolationPercentage() {
        return violationPercentage;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        TestMeasure testMeasure = (TestMeasure) o;
        return Objects.equals(this.name, testMeasure.name) &&
                Objects.equals(this.metricGroup, testMeasure.metricGroup) &&
                Objects.equals(this.value, testMeasure.value) &&
                Objects.equals(this.unit, testMeasure.unit) &&
                Objects.equals(this.expectedMin, testMeasure.expectedMin) &&
                Objects.equals(this.expectedMax, testMeasure.expectedMax) &&
                Objects.equals(this.numFailingOrInvalidatedRuns, testMeasure.numFailingOrInvalidatedRuns) &&
                Objects.equals(this.numValidRuns, testMeasure.numValidRuns) &&
                Objects.equals(this.numImprovedRuns, testMeasure.numImprovedRuns) &&
                Objects.equals(this.numDegradedRuns, testMeasure.numDegradedRuns) &&
                Objects.equals(this.violationPercentage, testMeasure.violationPercentage);
    }

    @Override
    public int hashCode() {
        return Objects.hash(name, metricGroup, value, unit, expectedMin, expectedMax, numFailingOrInvalidatedRuns, numValidRuns, numImprovedRuns, numDegradedRuns, violationPercentage);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class TestMeasure {\n");

        sb.append("    name: ").append(PerfSigUIUtils.toIndentedString(name)).append("\n");
        sb.append("    metricGroup: ").append(PerfSigUIUtils.toIndentedString(metricGroup)).append("\n");
        sb.append("    value: ").append(PerfSigUIUtils.toIndentedString(value)).append("\n");
        sb.append("    unit: ").append(PerfSigUIUtils.toIndentedString(unit)).append("\n");
        sb.append("    expectedMin: ").append(PerfSigUIUtils.toIndentedString(expectedMin)).append("\n");
        sb.append("    expectedMax: ").append(PerfSigUIUtils.toIndentedString(expectedMax)).append("\n");
        sb.append("    numFailingOrInvalidatedRuns: ").append(PerfSigUIUtils.toIndentedString(numFailingOrInvalidatedRuns)).append("\n");
        sb.append("    numValidRuns: ").append(PerfSigUIUtils.toIndentedString(numValidRuns)).append("\n");
        sb.append("    numImprovedRuns: ").append(PerfSigUIUtils.toIndentedString(numImprovedRuns)).append("\n");
        sb.append("    numDegradedRuns: ").append(PerfSigUIUtils.toIndentedString(numDegradedRuns)).append("\n");
        sb.append("    violationPercentage: ").append(PerfSigUIUtils.toIndentedString(violationPercentage)).append("\n");
        sb.append("}");
        return sb.toString();
    }
}
